CREATE DATABASE FUREVERFAMILY;
GO

USE FUREVERFAMILY
GO

CREATE TABLE USERS (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] NVARCHAR(100) NOT NULL UNIQUE,
	[PASSWORD] NVARCHAR(255) NOT NULL,
	ROLE NVARCHAR(50) NOT NULL DEFAULT 'adopter'
)



INSERT INTO USERS (NAME, PASSWORD) 
VALUES ('admin', 'admin123');

SELECT * FROM USERS

SELECT NAME, PASSWORD FROM users;